version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "deps"
    groups:
      google-grpc:
        patterns:
          - "google.golang.org/grpc*"
          - "google.golang.org/protobuf*"
          - "google.golang.org/genproto*"
      otel:
        patterns:
          - "go.opentelemetry.io/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"
