// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: kubemq.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequestType int32

const (
	StreamRequestType_StreamRequestTypeUnknown StreamRequestType = 0
	StreamRequestType_ReceiveMessage           StreamRequestType = 1
	StreamRequestType_AckMessage               StreamRequestType = 2
	StreamRequestType_RejectMessage            StreamRequestType = 3
	StreamRequestType_ModifyVisibility         StreamRequestType = 4
	StreamRequestType_ResendMessage            StreamRequestType = 5
	StreamRequestType_SendModifiedMessage      StreamRequestType = 6
)

// Enum value maps for StreamRequestType.
var (
	StreamRequestType_name = map[int32]string{
		0: "StreamRequestTypeUnknown",
		1: "ReceiveMessage",
		2: "AckMessage",
		3: "RejectMessage",
		4: "ModifyVisibility",
		5: "ResendMessage",
		6: "SendModifiedMessage",
	}
	StreamRequestType_value = map[string]int32{
		"StreamRequestTypeUnknown": 0,
		"ReceiveMessage":           1,
		"AckMessage":               2,
		"RejectMessage":            3,
		"ModifyVisibility":         4,
		"ResendMessage":            5,
		"SendModifiedMessage":      6,
	}
)

func (x StreamRequestType) Enum() *StreamRequestType {
	p := new(StreamRequestType)
	*p = x
	return p
}

func (x StreamRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_kubemq_proto_enumTypes[0].Descriptor()
}

func (StreamRequestType) Type() protoreflect.EnumType {
	return &file_kubemq_proto_enumTypes[0]
}

func (x StreamRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamRequestType.Descriptor instead.
func (StreamRequestType) EnumDescriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{0}
}

type QueuesDownstreamRequestType int32

const (
	QueuesDownstreamRequestType_PollRequestTypeUnknown QueuesDownstreamRequestType = 0
	QueuesDownstreamRequestType_Get                    QueuesDownstreamRequestType = 1
	QueuesDownstreamRequestType_AckAll                 QueuesDownstreamRequestType = 2
	QueuesDownstreamRequestType_AckRange               QueuesDownstreamRequestType = 3
	QueuesDownstreamRequestType_NAckAll                QueuesDownstreamRequestType = 4
	QueuesDownstreamRequestType_NAckRange              QueuesDownstreamRequestType = 5
	QueuesDownstreamRequestType_ReQueueAll             QueuesDownstreamRequestType = 6
	QueuesDownstreamRequestType_ReQueueRange           QueuesDownstreamRequestType = 7
	QueuesDownstreamRequestType_ActiveOffsets          QueuesDownstreamRequestType = 8
	QueuesDownstreamRequestType_TransactionStatus      QueuesDownstreamRequestType = 9
	QueuesDownstreamRequestType_CloseByClient          QueuesDownstreamRequestType = 10
	QueuesDownstreamRequestType_CloseByServer          QueuesDownstreamRequestType = 11
)

// Enum value maps for QueuesDownstreamRequestType.
var (
	QueuesDownstreamRequestType_name = map[int32]string{
		0:  "PollRequestTypeUnknown",
		1:  "Get",
		2:  "AckAll",
		3:  "AckRange",
		4:  "NAckAll",
		5:  "NAckRange",
		6:  "ReQueueAll",
		7:  "ReQueueRange",
		8:  "ActiveOffsets",
		9:  "TransactionStatus",
		10: "CloseByClient",
		11: "CloseByServer",
	}
	QueuesDownstreamRequestType_value = map[string]int32{
		"PollRequestTypeUnknown": 0,
		"Get":                    1,
		"AckAll":                 2,
		"AckRange":               3,
		"NAckAll":                4,
		"NAckRange":              5,
		"ReQueueAll":             6,
		"ReQueueRange":           7,
		"ActiveOffsets":          8,
		"TransactionStatus":      9,
		"CloseByClient":          10,
		"CloseByServer":          11,
	}
)

func (x QueuesDownstreamRequestType) Enum() *QueuesDownstreamRequestType {
	p := new(QueuesDownstreamRequestType)
	*p = x
	return p
}

func (x QueuesDownstreamRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueuesDownstreamRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_kubemq_proto_enumTypes[1].Descriptor()
}

func (QueuesDownstreamRequestType) Type() protoreflect.EnumType {
	return &file_kubemq_proto_enumTypes[1]
}

func (x QueuesDownstreamRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueuesDownstreamRequestType.Descriptor instead.
func (QueuesDownstreamRequestType) EnumDescriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{1}
}

type Subscribe_SubscribeType int32

const (
	Subscribe_SubscribeTypeUndefined Subscribe_SubscribeType = 0
	Subscribe_Events                 Subscribe_SubscribeType = 1
	Subscribe_EventsStore            Subscribe_SubscribeType = 2
	Subscribe_Commands               Subscribe_SubscribeType = 3
	Subscribe_Queries                Subscribe_SubscribeType = 4
)

// Enum value maps for Subscribe_SubscribeType.
var (
	Subscribe_SubscribeType_name = map[int32]string{
		0: "SubscribeTypeUndefined",
		1: "Events",
		2: "EventsStore",
		3: "Commands",
		4: "Queries",
	}
	Subscribe_SubscribeType_value = map[string]int32{
		"SubscribeTypeUndefined": 0,
		"Events":                 1,
		"EventsStore":            2,
		"Commands":               3,
		"Queries":                4,
	}
)

func (x Subscribe_SubscribeType) Enum() *Subscribe_SubscribeType {
	p := new(Subscribe_SubscribeType)
	*p = x
	return p
}

func (x Subscribe_SubscribeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Subscribe_SubscribeType) Descriptor() protoreflect.EnumDescriptor {
	return file_kubemq_proto_enumTypes[2].Descriptor()
}

func (Subscribe_SubscribeType) Type() protoreflect.EnumType {
	return &file_kubemq_proto_enumTypes[2]
}

func (x Subscribe_SubscribeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Subscribe_SubscribeType.Descriptor instead.
func (Subscribe_SubscribeType) EnumDescriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{5, 0}
}

type Subscribe_EventsStoreType int32

const (
	Subscribe_EventsStoreTypeUndefined Subscribe_EventsStoreType = 0
	Subscribe_StartNewOnly             Subscribe_EventsStoreType = 1
	Subscribe_StartFromFirst           Subscribe_EventsStoreType = 2
	Subscribe_StartFromLast            Subscribe_EventsStoreType = 3
	Subscribe_StartAtSequence          Subscribe_EventsStoreType = 4
	Subscribe_StartAtTime              Subscribe_EventsStoreType = 5
	Subscribe_StartAtTimeDelta         Subscribe_EventsStoreType = 6
)

// Enum value maps for Subscribe_EventsStoreType.
var (
	Subscribe_EventsStoreType_name = map[int32]string{
		0: "EventsStoreTypeUndefined",
		1: "StartNewOnly",
		2: "StartFromFirst",
		3: "StartFromLast",
		4: "StartAtSequence",
		5: "StartAtTime",
		6: "StartAtTimeDelta",
	}
	Subscribe_EventsStoreType_value = map[string]int32{
		"EventsStoreTypeUndefined": 0,
		"StartNewOnly":             1,
		"StartFromFirst":           2,
		"StartFromLast":            3,
		"StartAtSequence":          4,
		"StartAtTime":              5,
		"StartAtTimeDelta":         6,
	}
)

func (x Subscribe_EventsStoreType) Enum() *Subscribe_EventsStoreType {
	p := new(Subscribe_EventsStoreType)
	*p = x
	return p
}

func (x Subscribe_EventsStoreType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Subscribe_EventsStoreType) Descriptor() protoreflect.EnumDescriptor {
	return file_kubemq_proto_enumTypes[3].Descriptor()
}

func (Subscribe_EventsStoreType) Type() protoreflect.EnumType {
	return &file_kubemq_proto_enumTypes[3]
}

func (x Subscribe_EventsStoreType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Subscribe_EventsStoreType.Descriptor instead.
func (Subscribe_EventsStoreType) EnumDescriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{5, 1}
}

type Request_RequestType int32

const (
	Request_RequestTypeUnknown Request_RequestType = 0
	Request_Command            Request_RequestType = 1
	Request_Query              Request_RequestType = 2
)

// Enum value maps for Request_RequestType.
var (
	Request_RequestType_name = map[int32]string{
		0: "RequestTypeUnknown",
		1: "Command",
		2: "Query",
	}
	Request_RequestType_value = map[string]int32{
		"RequestTypeUnknown": 0,
		"Command":            1,
		"Query":              2,
	}
)

func (x Request_RequestType) Enum() *Request_RequestType {
	p := new(Request_RequestType)
	*p = x
	return p
}

func (x Request_RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Request_RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_kubemq_proto_enumTypes[4].Descriptor()
}

func (Request_RequestType) Type() protoreflect.EnumType {
	return &file_kubemq_proto_enumTypes[4]
}

func (x Request_RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Request_RequestType.Descriptor instead.
func (Request_RequestType) EnumDescriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{6, 0}
}

type PingResult struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Host                string                 `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	Version             string                 `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	ServerStartTime     int64                  `protobuf:"varint,3,opt,name=ServerStartTime,proto3" json:"ServerStartTime,omitempty"`
	ServerUpTimeSeconds int64                  `protobuf:"varint,4,opt,name=ServerUpTimeSeconds,proto3" json:"ServerUpTimeSeconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PingResult) Reset() {
	*x = PingResult{}
	mi := &file_kubemq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResult) ProtoMessage() {}

func (x *PingResult) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResult.ProtoReflect.Descriptor instead.
func (*PingResult) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{0}
}

func (x *PingResult) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PingResult) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResult) GetServerStartTime() int64 {
	if x != nil {
		return x.ServerStartTime
	}
	return 0
}

func (x *PingResult) GetServerUpTimeSeconds() int64 {
	if x != nil {
		return x.ServerUpTimeSeconds
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_kubemq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{1}
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventID       string                 `protobuf:"bytes,1,opt,name=EventID,proto3" json:"EventID,omitempty"`
	Sent          bool                   `protobuf:"varint,2,opt,name=Sent,proto3" json:"Sent,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_kubemq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *Result) GetSent() bool {
	if x != nil {
		return x.Sent
	}
	return false
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventID       string                 `protobuf:"bytes,1,opt,name=EventID,proto3" json:"EventID,omitempty"`
	ClientID      string                 `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=Channel,proto3" json:"Channel,omitempty"`
	Metadata      string                 `protobuf:"bytes,4,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	Body          []byte                 `protobuf:"bytes,5,opt,name=Body,proto3" json:"Body,omitempty"`
	Store         bool                   `protobuf:"varint,6,opt,name=Store,proto3" json:"Store,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,7,rep,name=Tags,proto3" json:"Tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_kubemq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *Event) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *Event) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Event) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Event) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Event) GetStore() bool {
	if x != nil {
		return x.Store
	}
	return false
}

func (x *Event) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type EventReceive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventID       string                 `protobuf:"bytes,1,opt,name=EventID,proto3" json:"EventID,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=Channel,proto3" json:"Channel,omitempty"`
	Metadata      string                 `protobuf:"bytes,3,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=Body,proto3" json:"Body,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Sequence      uint64                 `protobuf:"varint,6,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,7,rep,name=Tags,proto3" json:"Tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventReceive) Reset() {
	*x = EventReceive{}
	mi := &file_kubemq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReceive) ProtoMessage() {}

func (x *EventReceive) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReceive.ProtoReflect.Descriptor instead.
func (*EventReceive) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{4}
}

func (x *EventReceive) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *EventReceive) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *EventReceive) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *EventReceive) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *EventReceive) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *EventReceive) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *EventReceive) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Subscribe struct {
	state                protoimpl.MessageState    `protogen:"open.v1"`
	SubscribeTypeData    Subscribe_SubscribeType   `protobuf:"varint,1,opt,name=SubscribeTypeData,proto3,enum=kubemq.Subscribe_SubscribeType" json:"SubscribeTypeData,omitempty"`
	ClientID             string                    `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Channel              string                    `protobuf:"bytes,3,opt,name=Channel,proto3" json:"Channel,omitempty"`
	Group                string                    `protobuf:"bytes,4,opt,name=Group,proto3" json:"Group,omitempty"`
	EventsStoreTypeData  Subscribe_EventsStoreType `protobuf:"varint,5,opt,name=EventsStoreTypeData,proto3,enum=kubemq.Subscribe_EventsStoreType" json:"EventsStoreTypeData,omitempty"`
	EventsStoreTypeValue int64                     `protobuf:"varint,6,opt,name=EventsStoreTypeValue,proto3" json:"EventsStoreTypeValue,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_kubemq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{5}
}

func (x *Subscribe) GetSubscribeTypeData() Subscribe_SubscribeType {
	if x != nil {
		return x.SubscribeTypeData
	}
	return Subscribe_SubscribeTypeUndefined
}

func (x *Subscribe) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *Subscribe) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Subscribe) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Subscribe) GetEventsStoreTypeData() Subscribe_EventsStoreType {
	if x != nil {
		return x.EventsStoreTypeData
	}
	return Subscribe_EventsStoreTypeUndefined
}

func (x *Subscribe) GetEventsStoreTypeValue() int64 {
	if x != nil {
		return x.EventsStoreTypeValue
	}
	return 0
}

type Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestID       string                 `protobuf:"bytes,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	RequestTypeData Request_RequestType    `protobuf:"varint,2,opt,name=RequestTypeData,proto3,enum=kubemq.Request_RequestType" json:"RequestTypeData,omitempty"`
	ClientID        string                 `protobuf:"bytes,3,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Channel         string                 `protobuf:"bytes,4,opt,name=Channel,proto3" json:"Channel,omitempty"`
	Metadata        string                 `protobuf:"bytes,5,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	Body            []byte                 `protobuf:"bytes,6,opt,name=Body,proto3" json:"Body,omitempty"`
	ReplyChannel    string                 `protobuf:"bytes,7,opt,name=ReplyChannel,proto3" json:"ReplyChannel,omitempty"`
	Timeout         int32                  `protobuf:"varint,8,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	CacheKey        string                 `protobuf:"bytes,9,opt,name=CacheKey,proto3" json:"CacheKey,omitempty"`
	CacheTTL        int32                  `protobuf:"varint,10,opt,name=CacheTTL,proto3" json:"CacheTTL,omitempty"`
	Span            []byte                 `protobuf:"bytes,11,opt,name=Span,proto3" json:"Span,omitempty"`
	Tags            map[string]string      `protobuf:"bytes,12,rep,name=Tags,proto3" json:"Tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_kubemq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{6}
}

func (x *Request) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *Request) GetRequestTypeData() Request_RequestType {
	if x != nil {
		return x.RequestTypeData
	}
	return Request_RequestTypeUnknown
}

func (x *Request) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *Request) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Request) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Request) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Request) GetReplyChannel() string {
	if x != nil {
		return x.ReplyChannel
	}
	return ""
}

func (x *Request) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *Request) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

func (x *Request) GetCacheTTL() int32 {
	if x != nil {
		return x.CacheTTL
	}
	return 0
}

func (x *Request) GetSpan() []byte {
	if x != nil {
		return x.Span
	}
	return nil
}

func (x *Request) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	RequestID     string                 `protobuf:"bytes,2,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	ReplyChannel  string                 `protobuf:"bytes,3,opt,name=ReplyChannel,proto3" json:"ReplyChannel,omitempty"`
	Metadata      string                 `protobuf:"bytes,4,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	Body          []byte                 `protobuf:"bytes,5,opt,name=Body,proto3" json:"Body,omitempty"`
	CacheHit      bool                   `protobuf:"varint,6,opt,name=CacheHit,proto3" json:"CacheHit,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Executed      bool                   `protobuf:"varint,8,opt,name=Executed,proto3" json:"Executed,omitempty"`
	Error         string                 `protobuf:"bytes,9,opt,name=Error,proto3" json:"Error,omitempty"`
	Span          []byte                 `protobuf:"bytes,10,opt,name=Span,proto3" json:"Span,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,11,rep,name=Tags,proto3" json:"Tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_kubemq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{7}
}

func (x *Response) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *Response) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *Response) GetReplyChannel() string {
	if x != nil {
		return x.ReplyChannel
	}
	return ""
}

func (x *Response) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Response) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Response) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *Response) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Response) GetExecuted() bool {
	if x != nil {
		return x.Executed
	}
	return false
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Response) GetSpan() []byte {
	if x != nil {
		return x.Span
	}
	return nil
}

func (x *Response) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type QueueMessage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	MessageID     string                  `protobuf:"bytes,1,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	ClientID      string                  `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Channel       string                  `protobuf:"bytes,3,opt,name=Channel,proto3" json:"Channel,omitempty"`
	Metadata      string                  `protobuf:"bytes,4,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	Body          []byte                  `protobuf:"bytes,5,opt,name=Body,proto3" json:"Body,omitempty"`
	Tags          map[string]string       `protobuf:"bytes,6,rep,name=Tags,proto3" json:"Tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Attributes    *QueueMessageAttributes `protobuf:"bytes,7,opt,name=Attributes,proto3" json:"Attributes,omitempty"`
	Policy        *QueueMessagePolicy     `protobuf:"bytes,8,opt,name=Policy,proto3" json:"Policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMessage) Reset() {
	*x = QueueMessage{}
	mi := &file_kubemq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMessage) ProtoMessage() {}

func (x *QueueMessage) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMessage.ProtoReflect.Descriptor instead.
func (*QueueMessage) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{8}
}

func (x *QueueMessage) GetMessageID() string {
	if x != nil {
		return x.MessageID
	}
	return ""
}

func (x *QueueMessage) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *QueueMessage) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *QueueMessage) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *QueueMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *QueueMessage) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *QueueMessage) GetAttributes() *QueueMessageAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *QueueMessage) GetPolicy() *QueueMessagePolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type QueueMessagesBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchID       string                 `protobuf:"bytes,1,opt,name=BatchID,proto3" json:"BatchID,omitempty"`
	Messages      []*QueueMessage        `protobuf:"bytes,2,rep,name=Messages,proto3" json:"Messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMessagesBatchRequest) Reset() {
	*x = QueueMessagesBatchRequest{}
	mi := &file_kubemq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMessagesBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMessagesBatchRequest) ProtoMessage() {}

func (x *QueueMessagesBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMessagesBatchRequest.ProtoReflect.Descriptor instead.
func (*QueueMessagesBatchRequest) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{9}
}

func (x *QueueMessagesBatchRequest) GetBatchID() string {
	if x != nil {
		return x.BatchID
	}
	return ""
}

func (x *QueueMessagesBatchRequest) GetMessages() []*QueueMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type QueueMessagesBatchResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	BatchID       string                    `protobuf:"bytes,1,opt,name=BatchID,proto3" json:"BatchID,omitempty"`
	Results       []*SendQueueMessageResult `protobuf:"bytes,2,rep,name=Results,proto3" json:"Results,omitempty"`
	HaveErrors    bool                      `protobuf:"varint,3,opt,name=HaveErrors,proto3" json:"HaveErrors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMessagesBatchResponse) Reset() {
	*x = QueueMessagesBatchResponse{}
	mi := &file_kubemq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMessagesBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMessagesBatchResponse) ProtoMessage() {}

func (x *QueueMessagesBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMessagesBatchResponse.ProtoReflect.Descriptor instead.
func (*QueueMessagesBatchResponse) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{10}
}

func (x *QueueMessagesBatchResponse) GetBatchID() string {
	if x != nil {
		return x.BatchID
	}
	return ""
}

func (x *QueueMessagesBatchResponse) GetResults() []*SendQueueMessageResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *QueueMessagesBatchResponse) GetHaveErrors() bool {
	if x != nil {
		return x.HaveErrors
	}
	return false
}

type QueueMessageAttributes struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Timestamp         int64                  `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Sequence          uint64                 `protobuf:"varint,2,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
	MD5OfBody         string                 `protobuf:"bytes,3,opt,name=MD5OfBody,proto3" json:"MD5OfBody,omitempty"`
	ReceiveCount      int32                  `protobuf:"varint,4,opt,name=ReceiveCount,proto3" json:"ReceiveCount,omitempty"`
	ReRouted          bool                   `protobuf:"varint,5,opt,name=ReRouted,proto3" json:"ReRouted,omitempty"`
	ReRoutedFromQueue string                 `protobuf:"bytes,6,opt,name=ReRoutedFromQueue,proto3" json:"ReRoutedFromQueue,omitempty"`
	ExpirationAt      int64                  `protobuf:"varint,7,opt,name=ExpirationAt,proto3" json:"ExpirationAt,omitempty"`
	DelayedTo         int64                  `protobuf:"varint,8,opt,name=DelayedTo,proto3" json:"DelayedTo,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueueMessageAttributes) Reset() {
	*x = QueueMessageAttributes{}
	mi := &file_kubemq_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMessageAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMessageAttributes) ProtoMessage() {}

func (x *QueueMessageAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMessageAttributes.ProtoReflect.Descriptor instead.
func (*QueueMessageAttributes) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{11}
}

func (x *QueueMessageAttributes) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *QueueMessageAttributes) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *QueueMessageAttributes) GetMD5OfBody() string {
	if x != nil {
		return x.MD5OfBody
	}
	return ""
}

func (x *QueueMessageAttributes) GetReceiveCount() int32 {
	if x != nil {
		return x.ReceiveCount
	}
	return 0
}

func (x *QueueMessageAttributes) GetReRouted() bool {
	if x != nil {
		return x.ReRouted
	}
	return false
}

func (x *QueueMessageAttributes) GetReRoutedFromQueue() string {
	if x != nil {
		return x.ReRoutedFromQueue
	}
	return ""
}

func (x *QueueMessageAttributes) GetExpirationAt() int64 {
	if x != nil {
		return x.ExpirationAt
	}
	return 0
}

func (x *QueueMessageAttributes) GetDelayedTo() int64 {
	if x != nil {
		return x.DelayedTo
	}
	return 0
}

type QueueMessagePolicy struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExpirationSeconds int32                  `protobuf:"varint,1,opt,name=ExpirationSeconds,proto3" json:"ExpirationSeconds,omitempty"`
	DelaySeconds      int32                  `protobuf:"varint,2,opt,name=DelaySeconds,proto3" json:"DelaySeconds,omitempty"`
	MaxReceiveCount   int32                  `protobuf:"varint,3,opt,name=MaxReceiveCount,proto3" json:"MaxReceiveCount,omitempty"`
	MaxReceiveQueue   string                 `protobuf:"bytes,4,opt,name=MaxReceiveQueue,proto3" json:"MaxReceiveQueue,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueueMessagePolicy) Reset() {
	*x = QueueMessagePolicy{}
	mi := &file_kubemq_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMessagePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMessagePolicy) ProtoMessage() {}

func (x *QueueMessagePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMessagePolicy.ProtoReflect.Descriptor instead.
func (*QueueMessagePolicy) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{12}
}

func (x *QueueMessagePolicy) GetExpirationSeconds() int32 {
	if x != nil {
		return x.ExpirationSeconds
	}
	return 0
}

func (x *QueueMessagePolicy) GetDelaySeconds() int32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *QueueMessagePolicy) GetMaxReceiveCount() int32 {
	if x != nil {
		return x.MaxReceiveCount
	}
	return 0
}

func (x *QueueMessagePolicy) GetMaxReceiveQueue() string {
	if x != nil {
		return x.MaxReceiveQueue
	}
	return ""
}

type SendQueueMessageResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageID     string                 `protobuf:"bytes,1,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	SentAt        int64                  `protobuf:"varint,2,opt,name=SentAt,proto3" json:"SentAt,omitempty"`
	ExpirationAt  int64                  `protobuf:"varint,3,opt,name=ExpirationAt,proto3" json:"ExpirationAt,omitempty"`
	DelayedTo     int64                  `protobuf:"varint,4,opt,name=DelayedTo,proto3" json:"DelayedTo,omitempty"`
	IsError       bool                   `protobuf:"varint,5,opt,name=IsError,proto3" json:"IsError,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendQueueMessageResult) Reset() {
	*x = SendQueueMessageResult{}
	mi := &file_kubemq_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendQueueMessageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendQueueMessageResult) ProtoMessage() {}

func (x *SendQueueMessageResult) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendQueueMessageResult.ProtoReflect.Descriptor instead.
func (*SendQueueMessageResult) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{13}
}

func (x *SendQueueMessageResult) GetMessageID() string {
	if x != nil {
		return x.MessageID
	}
	return ""
}

func (x *SendQueueMessageResult) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

func (x *SendQueueMessageResult) GetExpirationAt() int64 {
	if x != nil {
		return x.ExpirationAt
	}
	return 0
}

func (x *SendQueueMessageResult) GetDelayedTo() int64 {
	if x != nil {
		return x.DelayedTo
	}
	return 0
}

func (x *SendQueueMessageResult) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *SendQueueMessageResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReceiveQueueMessagesRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RequestID           string                 `protobuf:"bytes,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	ClientID            string                 `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Channel             string                 `protobuf:"bytes,3,opt,name=Channel,proto3" json:"Channel,omitempty"`
	MaxNumberOfMessages int32                  `protobuf:"varint,4,opt,name=MaxNumberOfMessages,proto3" json:"MaxNumberOfMessages,omitempty"`
	WaitTimeSeconds     int32                  `protobuf:"varint,5,opt,name=WaitTimeSeconds,proto3" json:"WaitTimeSeconds,omitempty"`
	IsPeak              bool                   `protobuf:"varint,6,opt,name=IsPeak,proto3" json:"IsPeak,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReceiveQueueMessagesRequest) Reset() {
	*x = ReceiveQueueMessagesRequest{}
	mi := &file_kubemq_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveQueueMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveQueueMessagesRequest) ProtoMessage() {}

func (x *ReceiveQueueMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveQueueMessagesRequest.ProtoReflect.Descriptor instead.
func (*ReceiveQueueMessagesRequest) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{14}
}

func (x *ReceiveQueueMessagesRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *ReceiveQueueMessagesRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *ReceiveQueueMessagesRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ReceiveQueueMessagesRequest) GetMaxNumberOfMessages() int32 {
	if x != nil {
		return x.MaxNumberOfMessages
	}
	return 0
}

func (x *ReceiveQueueMessagesRequest) GetWaitTimeSeconds() int32 {
	if x != nil {
		return x.WaitTimeSeconds
	}
	return 0
}

func (x *ReceiveQueueMessagesRequest) GetIsPeak() bool {
	if x != nil {
		return x.IsPeak
	}
	return false
}

type ReceiveQueueMessagesResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestID        string                 `protobuf:"bytes,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	Messages         []*QueueMessage        `protobuf:"bytes,2,rep,name=Messages,proto3" json:"Messages,omitempty"`
	MessagesReceived int32                  `protobuf:"varint,3,opt,name=MessagesReceived,proto3" json:"MessagesReceived,omitempty"`
	MessagesExpired  int32                  `protobuf:"varint,4,opt,name=MessagesExpired,proto3" json:"MessagesExpired,omitempty"`
	IsPeak           bool                   `protobuf:"varint,5,opt,name=IsPeak,proto3" json:"IsPeak,omitempty"`
	IsError          bool                   `protobuf:"varint,6,opt,name=IsError,proto3" json:"IsError,omitempty"`
	Error            string                 `protobuf:"bytes,7,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReceiveQueueMessagesResponse) Reset() {
	*x = ReceiveQueueMessagesResponse{}
	mi := &file_kubemq_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveQueueMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveQueueMessagesResponse) ProtoMessage() {}

func (x *ReceiveQueueMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveQueueMessagesResponse.ProtoReflect.Descriptor instead.
func (*ReceiveQueueMessagesResponse) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{15}
}

func (x *ReceiveQueueMessagesResponse) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *ReceiveQueueMessagesResponse) GetMessages() []*QueueMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ReceiveQueueMessagesResponse) GetMessagesReceived() int32 {
	if x != nil {
		return x.MessagesReceived
	}
	return 0
}

func (x *ReceiveQueueMessagesResponse) GetMessagesExpired() int32 {
	if x != nil {
		return x.MessagesExpired
	}
	return 0
}

func (x *ReceiveQueueMessagesResponse) GetIsPeak() bool {
	if x != nil {
		return x.IsPeak
	}
	return false
}

func (x *ReceiveQueueMessagesResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *ReceiveQueueMessagesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AckAllQueueMessagesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestID       string                 `protobuf:"bytes,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	ClientID        string                 `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Channel         string                 `protobuf:"bytes,3,opt,name=Channel,proto3" json:"Channel,omitempty"`
	WaitTimeSeconds int32                  `protobuf:"varint,4,opt,name=WaitTimeSeconds,proto3" json:"WaitTimeSeconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AckAllQueueMessagesRequest) Reset() {
	*x = AckAllQueueMessagesRequest{}
	mi := &file_kubemq_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckAllQueueMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckAllQueueMessagesRequest) ProtoMessage() {}

func (x *AckAllQueueMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckAllQueueMessagesRequest.ProtoReflect.Descriptor instead.
func (*AckAllQueueMessagesRequest) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{16}
}

func (x *AckAllQueueMessagesRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *AckAllQueueMessagesRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *AckAllQueueMessagesRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *AckAllQueueMessagesRequest) GetWaitTimeSeconds() int32 {
	if x != nil {
		return x.WaitTimeSeconds
	}
	return 0
}

type AckAllQueueMessagesResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestID        string                 `protobuf:"bytes,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	AffectedMessages uint64                 `protobuf:"varint,2,opt,name=AffectedMessages,proto3" json:"AffectedMessages,omitempty"`
	IsError          bool                   `protobuf:"varint,3,opt,name=IsError,proto3" json:"IsError,omitempty"`
	Error            string                 `protobuf:"bytes,4,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AckAllQueueMessagesResponse) Reset() {
	*x = AckAllQueueMessagesResponse{}
	mi := &file_kubemq_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckAllQueueMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckAllQueueMessagesResponse) ProtoMessage() {}

func (x *AckAllQueueMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckAllQueueMessagesResponse.ProtoReflect.Descriptor instead.
func (*AckAllQueueMessagesResponse) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{17}
}

func (x *AckAllQueueMessagesResponse) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *AckAllQueueMessagesResponse) GetAffectedMessages() uint64 {
	if x != nil {
		return x.AffectedMessages
	}
	return 0
}

func (x *AckAllQueueMessagesResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *AckAllQueueMessagesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StreamQueueMessagesRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RequestID             string                 `protobuf:"bytes,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	ClientID              string                 `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	StreamRequestTypeData StreamRequestType      `protobuf:"varint,3,opt,name=StreamRequestTypeData,proto3,enum=kubemq.StreamRequestType" json:"StreamRequestTypeData,omitempty"`
	Channel               string                 `protobuf:"bytes,4,opt,name=Channel,proto3" json:"Channel,omitempty"`
	VisibilitySeconds     int32                  `protobuf:"varint,5,opt,name=VisibilitySeconds,proto3" json:"VisibilitySeconds,omitempty"`
	WaitTimeSeconds       int32                  `protobuf:"varint,6,opt,name=WaitTimeSeconds,proto3" json:"WaitTimeSeconds,omitempty"`
	RefSequence           uint64                 `protobuf:"varint,7,opt,name=RefSequence,proto3" json:"RefSequence,omitempty"`
	ModifiedMessage       *QueueMessage          `protobuf:"bytes,8,opt,name=ModifiedMessage,proto3" json:"ModifiedMessage,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StreamQueueMessagesRequest) Reset() {
	*x = StreamQueueMessagesRequest{}
	mi := &file_kubemq_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamQueueMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamQueueMessagesRequest) ProtoMessage() {}

func (x *StreamQueueMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamQueueMessagesRequest.ProtoReflect.Descriptor instead.
func (*StreamQueueMessagesRequest) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{18}
}

func (x *StreamQueueMessagesRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *StreamQueueMessagesRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *StreamQueueMessagesRequest) GetStreamRequestTypeData() StreamRequestType {
	if x != nil {
		return x.StreamRequestTypeData
	}
	return StreamRequestType_StreamRequestTypeUnknown
}

func (x *StreamQueueMessagesRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *StreamQueueMessagesRequest) GetVisibilitySeconds() int32 {
	if x != nil {
		return x.VisibilitySeconds
	}
	return 0
}

func (x *StreamQueueMessagesRequest) GetWaitTimeSeconds() int32 {
	if x != nil {
		return x.WaitTimeSeconds
	}
	return 0
}

func (x *StreamQueueMessagesRequest) GetRefSequence() uint64 {
	if x != nil {
		return x.RefSequence
	}
	return 0
}

func (x *StreamQueueMessagesRequest) GetModifiedMessage() *QueueMessage {
	if x != nil {
		return x.ModifiedMessage
	}
	return nil
}

type StreamQueueMessagesResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RequestID             string                 `protobuf:"bytes,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	StreamRequestTypeData StreamRequestType      `protobuf:"varint,2,opt,name=StreamRequestTypeData,proto3,enum=kubemq.StreamRequestType" json:"StreamRequestTypeData,omitempty"`
	Message               *QueueMessage          `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	IsError               bool                   `protobuf:"varint,4,opt,name=IsError,proto3" json:"IsError,omitempty"`
	Error                 string                 `protobuf:"bytes,5,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StreamQueueMessagesResponse) Reset() {
	*x = StreamQueueMessagesResponse{}
	mi := &file_kubemq_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamQueueMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamQueueMessagesResponse) ProtoMessage() {}

func (x *StreamQueueMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamQueueMessagesResponse.ProtoReflect.Descriptor instead.
func (*StreamQueueMessagesResponse) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{19}
}

func (x *StreamQueueMessagesResponse) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *StreamQueueMessagesResponse) GetStreamRequestTypeData() StreamRequestType {
	if x != nil {
		return x.StreamRequestTypeData
	}
	return StreamRequestType_StreamRequestTypeUnknown
}

func (x *StreamQueueMessagesResponse) GetMessage() *QueueMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StreamQueueMessagesResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *StreamQueueMessagesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type QueuesUpstreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestID     string                 `protobuf:"bytes,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	Messages      []*QueueMessage        `protobuf:"bytes,2,rep,name=Messages,proto3" json:"Messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueuesUpstreamRequest) Reset() {
	*x = QueuesUpstreamRequest{}
	mi := &file_kubemq_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuesUpstreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuesUpstreamRequest) ProtoMessage() {}

func (x *QueuesUpstreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuesUpstreamRequest.ProtoReflect.Descriptor instead.
func (*QueuesUpstreamRequest) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{20}
}

func (x *QueuesUpstreamRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *QueuesUpstreamRequest) GetMessages() []*QueueMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type QueuesUpstreamResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	RefRequestID  string                    `protobuf:"bytes,1,opt,name=RefRequestID,proto3" json:"RefRequestID,omitempty"`
	Results       []*SendQueueMessageResult `protobuf:"bytes,2,rep,name=Results,proto3" json:"Results,omitempty"`
	IsError       bool                      `protobuf:"varint,3,opt,name=IsError,proto3" json:"IsError,omitempty"`
	Error         string                    `protobuf:"bytes,4,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueuesUpstreamResponse) Reset() {
	*x = QueuesUpstreamResponse{}
	mi := &file_kubemq_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuesUpstreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuesUpstreamResponse) ProtoMessage() {}

func (x *QueuesUpstreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuesUpstreamResponse.ProtoReflect.Descriptor instead.
func (*QueuesUpstreamResponse) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{21}
}

func (x *QueuesUpstreamResponse) GetRefRequestID() string {
	if x != nil {
		return x.RefRequestID
	}
	return ""
}

func (x *QueuesUpstreamResponse) GetResults() []*SendQueueMessageResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *QueuesUpstreamResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *QueuesUpstreamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type QueuesDownstreamRequest struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	RequestID        string                      `protobuf:"bytes,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	ClientID         string                      `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	RequestTypeData  QueuesDownstreamRequestType `protobuf:"varint,3,opt,name=RequestTypeData,proto3,enum=kubemq.QueuesDownstreamRequestType" json:"RequestTypeData,omitempty"`
	Channel          string                      `protobuf:"bytes,4,opt,name=Channel,proto3" json:"Channel,omitempty"`
	MaxItems         int32                       `protobuf:"varint,5,opt,name=MaxItems,proto3" json:"MaxItems,omitempty"`
	WaitTimeout      int32                       `protobuf:"varint,6,opt,name=WaitTimeout,proto3" json:"WaitTimeout,omitempty"`
	AutoAck          bool                        `protobuf:"varint,7,opt,name=AutoAck,proto3" json:"AutoAck,omitempty"`
	ReQueueChannel   string                      `protobuf:"bytes,8,opt,name=ReQueueChannel,proto3" json:"ReQueueChannel,omitempty"`
	SequenceRange    []int64                     `protobuf:"varint,9,rep,packed,name=SequenceRange,proto3" json:"SequenceRange,omitempty"`
	RefTransactionId string                      `protobuf:"bytes,10,opt,name=RefTransactionId,proto3" json:"RefTransactionId,omitempty"`
	Metadata         map[string]string           `protobuf:"bytes,12,rep,name=Metadata,proto3" json:"Metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueuesDownstreamRequest) Reset() {
	*x = QueuesDownstreamRequest{}
	mi := &file_kubemq_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuesDownstreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuesDownstreamRequest) ProtoMessage() {}

func (x *QueuesDownstreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuesDownstreamRequest.ProtoReflect.Descriptor instead.
func (*QueuesDownstreamRequest) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{22}
}

func (x *QueuesDownstreamRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *QueuesDownstreamRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *QueuesDownstreamRequest) GetRequestTypeData() QueuesDownstreamRequestType {
	if x != nil {
		return x.RequestTypeData
	}
	return QueuesDownstreamRequestType_PollRequestTypeUnknown
}

func (x *QueuesDownstreamRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *QueuesDownstreamRequest) GetMaxItems() int32 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

func (x *QueuesDownstreamRequest) GetWaitTimeout() int32 {
	if x != nil {
		return x.WaitTimeout
	}
	return 0
}

func (x *QueuesDownstreamRequest) GetAutoAck() bool {
	if x != nil {
		return x.AutoAck
	}
	return false
}

func (x *QueuesDownstreamRequest) GetReQueueChannel() string {
	if x != nil {
		return x.ReQueueChannel
	}
	return ""
}

func (x *QueuesDownstreamRequest) GetSequenceRange() []int64 {
	if x != nil {
		return x.SequenceRange
	}
	return nil
}

func (x *QueuesDownstreamRequest) GetRefTransactionId() string {
	if x != nil {
		return x.RefTransactionId
	}
	return ""
}

func (x *QueuesDownstreamRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type QueuesDownstreamResponse struct {
	state               protoimpl.MessageState      `protogen:"open.v1"`
	TransactionId       string                      `protobuf:"bytes,1,opt,name=TransactionId,proto3" json:"TransactionId,omitempty"`
	RefRequestId        string                      `protobuf:"bytes,2,opt,name=RefRequestId,proto3" json:"RefRequestId,omitempty"`
	RequestTypeData     QueuesDownstreamRequestType `protobuf:"varint,3,opt,name=RequestTypeData,proto3,enum=kubemq.QueuesDownstreamRequestType" json:"RequestTypeData,omitempty"`
	Messages            []*QueueMessage             `protobuf:"bytes,4,rep,name=Messages,proto3" json:"Messages,omitempty"`
	ActiveOffsets       []int64                     `protobuf:"varint,5,rep,packed,name=ActiveOffsets,proto3" json:"ActiveOffsets,omitempty"`
	IsError             bool                        `protobuf:"varint,6,opt,name=IsError,proto3" json:"IsError,omitempty"`
	Error               string                      `protobuf:"bytes,7,opt,name=Error,proto3" json:"Error,omitempty"`
	TransactionComplete bool                        `protobuf:"varint,8,opt,name=TransactionComplete,proto3" json:"TransactionComplete,omitempty"`
	Metadata            map[string]string           `protobuf:"bytes,9,rep,name=Metadata,proto3" json:"Metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueuesDownstreamResponse) Reset() {
	*x = QueuesDownstreamResponse{}
	mi := &file_kubemq_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuesDownstreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuesDownstreamResponse) ProtoMessage() {}

func (x *QueuesDownstreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubemq_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuesDownstreamResponse.ProtoReflect.Descriptor instead.
func (*QueuesDownstreamResponse) Descriptor() ([]byte, []int) {
	return file_kubemq_proto_rawDescGZIP(), []int{23}
}

func (x *QueuesDownstreamResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *QueuesDownstreamResponse) GetRefRequestId() string {
	if x != nil {
		return x.RefRequestId
	}
	return ""
}

func (x *QueuesDownstreamResponse) GetRequestTypeData() QueuesDownstreamRequestType {
	if x != nil {
		return x.RequestTypeData
	}
	return QueuesDownstreamRequestType_PollRequestTypeUnknown
}

func (x *QueuesDownstreamResponse) GetMessages() []*QueueMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *QueuesDownstreamResponse) GetActiveOffsets() []int64 {
	if x != nil {
		return x.ActiveOffsets
	}
	return nil
}

func (x *QueuesDownstreamResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *QueuesDownstreamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *QueuesDownstreamResponse) GetTransactionComplete() bool {
	if x != nil {
		return x.TransactionComplete
	}
	return false
}

func (x *QueuesDownstreamResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_kubemq_proto protoreflect.FileDescriptor

const file_kubemq_proto_rawDesc = "" +
	"\n" +
	"\fkubemq.proto\x12\x06kubemq\"\x96\x01\n" +
	"\n" +
	"PingResult\x12\x12\n" +
	"\x04Host\x18\x01 \x01(\tR\x04Host\x12\x18\n" +
	"\aVersion\x18\x02 \x01(\tR\aVersion\x12(\n" +
	"\x0fServerStartTime\x18\x03 \x01(\x03R\x0fServerStartTime\x120\n" +
	"\x13ServerUpTimeSeconds\x18\x04 \x01(\x03R\x13ServerUpTimeSeconds\"\a\n" +
	"\x05Empty\"L\n" +
	"\x06Result\x12\x18\n" +
	"\aEventID\x18\x01 \x01(\tR\aEventID\x12\x12\n" +
	"\x04Sent\x18\x02 \x01(\bR\x04Sent\x12\x14\n" +
	"\x05Error\x18\x03 \x01(\tR\x05Error\"\x83\x02\n" +
	"\x05Event\x12\x18\n" +
	"\aEventID\x18\x01 \x01(\tR\aEventID\x12\x1a\n" +
	"\bClientID\x18\x02 \x01(\tR\bClientID\x12\x18\n" +
	"\aChannel\x18\x03 \x01(\tR\aChannel\x12\x1a\n" +
	"\bMetadata\x18\x04 \x01(\tR\bMetadata\x12\x12\n" +
	"\x04Body\x18\x05 \x01(\fR\x04Body\x12\x14\n" +
	"\x05Store\x18\x06 \x01(\bR\x05Store\x12+\n" +
	"\x04Tags\x18\a \x03(\v2\x17.kubemq.Event.TagsEntryR\x04Tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x99\x02\n" +
	"\fEventReceive\x12\x18\n" +
	"\aEventID\x18\x01 \x01(\tR\aEventID\x12\x18\n" +
	"\aChannel\x18\x02 \x01(\tR\aChannel\x12\x1a\n" +
	"\bMetadata\x18\x03 \x01(\tR\bMetadata\x12\x12\n" +
	"\x04Body\x18\x04 \x01(\fR\x04Body\x12\x1c\n" +
	"\tTimestamp\x18\x05 \x01(\x03R\tTimestamp\x12\x1a\n" +
	"\bSequence\x18\x06 \x01(\x04R\bSequence\x122\n" +
	"\x04Tags\x18\a \x03(\v2\x1e.kubemq.EventReceive.TagsEntryR\x04Tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x04\n" +
	"\tSubscribe\x12M\n" +
	"\x11SubscribeTypeData\x18\x01 \x01(\x0e2\x1f.kubemq.Subscribe.SubscribeTypeR\x11SubscribeTypeData\x12\x1a\n" +
	"\bClientID\x18\x02 \x01(\tR\bClientID\x12\x18\n" +
	"\aChannel\x18\x03 \x01(\tR\aChannel\x12\x14\n" +
	"\x05Group\x18\x04 \x01(\tR\x05Group\x12S\n" +
	"\x13EventsStoreTypeData\x18\x05 \x01(\x0e2!.kubemq.Subscribe.EventsStoreTypeR\x13EventsStoreTypeData\x122\n" +
	"\x14EventsStoreTypeValue\x18\x06 \x01(\x03R\x14EventsStoreTypeValue\"c\n" +
	"\rSubscribeType\x12\x1a\n" +
	"\x16SubscribeTypeUndefined\x10\x00\x12\n" +
	"\n" +
	"\x06Events\x10\x01\x12\x0f\n" +
	"\vEventsStore\x10\x02\x12\f\n" +
	"\bCommands\x10\x03\x12\v\n" +
	"\aQueries\x10\x04\"\xa4\x01\n" +
	"\x0fEventsStoreType\x12\x1c\n" +
	"\x18EventsStoreTypeUndefined\x10\x00\x12\x10\n" +
	"\fStartNewOnly\x10\x01\x12\x12\n" +
	"\x0eStartFromFirst\x10\x02\x12\x11\n" +
	"\rStartFromLast\x10\x03\x12\x13\n" +
	"\x0fStartAtSequence\x10\x04\x12\x0f\n" +
	"\vStartAtTime\x10\x05\x12\x14\n" +
	"\x10StartAtTimeDelta\x10\x06\"\x85\x04\n" +
	"\aRequest\x12\x1c\n" +
	"\tRequestID\x18\x01 \x01(\tR\tRequestID\x12E\n" +
	"\x0fRequestTypeData\x18\x02 \x01(\x0e2\x1b.kubemq.Request.RequestTypeR\x0fRequestTypeData\x12\x1a\n" +
	"\bClientID\x18\x03 \x01(\tR\bClientID\x12\x18\n" +
	"\aChannel\x18\x04 \x01(\tR\aChannel\x12\x1a\n" +
	"\bMetadata\x18\x05 \x01(\tR\bMetadata\x12\x12\n" +
	"\x04Body\x18\x06 \x01(\fR\x04Body\x12\"\n" +
	"\fReplyChannel\x18\a \x01(\tR\fReplyChannel\x12\x18\n" +
	"\aTimeout\x18\b \x01(\x05R\aTimeout\x12\x1a\n" +
	"\bCacheKey\x18\t \x01(\tR\bCacheKey\x12\x1a\n" +
	"\bCacheTTL\x18\n" +
	" \x01(\x05R\bCacheTTL\x12\x12\n" +
	"\x04Span\x18\v \x01(\fR\x04Span\x12-\n" +
	"\x04Tags\x18\f \x03(\v2\x19.kubemq.Request.TagsEntryR\x04Tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\vRequestType\x12\x16\n" +
	"\x12RequestTypeUnknown\x10\x00\x12\v\n" +
	"\aCommand\x10\x01\x12\t\n" +
	"\x05Query\x10\x02\"\x81\x03\n" +
	"\bResponse\x12\x1a\n" +
	"\bClientID\x18\x01 \x01(\tR\bClientID\x12\x1c\n" +
	"\tRequestID\x18\x02 \x01(\tR\tRequestID\x12\"\n" +
	"\fReplyChannel\x18\x03 \x01(\tR\fReplyChannel\x12\x1a\n" +
	"\bMetadata\x18\x04 \x01(\tR\bMetadata\x12\x12\n" +
	"\x04Body\x18\x05 \x01(\fR\x04Body\x12\x1a\n" +
	"\bCacheHit\x18\x06 \x01(\bR\bCacheHit\x12\x1c\n" +
	"\tTimestamp\x18\a \x01(\x03R\tTimestamp\x12\x1a\n" +
	"\bExecuted\x18\b \x01(\bR\bExecuted\x12\x14\n" +
	"\x05Error\x18\t \x01(\tR\x05Error\x12\x12\n" +
	"\x04Span\x18\n" +
	" \x01(\fR\x04Span\x12.\n" +
	"\x04Tags\x18\v \x03(\v2\x1a.kubemq.Response.TagsEntryR\x04Tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x02\n" +
	"\fQueueMessage\x12\x1c\n" +
	"\tMessageID\x18\x01 \x01(\tR\tMessageID\x12\x1a\n" +
	"\bClientID\x18\x02 \x01(\tR\bClientID\x12\x18\n" +
	"\aChannel\x18\x03 \x01(\tR\aChannel\x12\x1a\n" +
	"\bMetadata\x18\x04 \x01(\tR\bMetadata\x12\x12\n" +
	"\x04Body\x18\x05 \x01(\fR\x04Body\x122\n" +
	"\x04Tags\x18\x06 \x03(\v2\x1e.kubemq.QueueMessage.TagsEntryR\x04Tags\x12>\n" +
	"\n" +
	"Attributes\x18\a \x01(\v2\x1e.kubemq.QueueMessageAttributesR\n" +
	"Attributes\x122\n" +
	"\x06Policy\x18\b \x01(\v2\x1a.kubemq.QueueMessagePolicyR\x06Policy\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\x19QueueMessagesBatchRequest\x12\x18\n" +
	"\aBatchID\x18\x01 \x01(\tR\aBatchID\x120\n" +
	"\bMessages\x18\x02 \x03(\v2\x14.kubemq.QueueMessageR\bMessages\"\x90\x01\n" +
	"\x1aQueueMessagesBatchResponse\x12\x18\n" +
	"\aBatchID\x18\x01 \x01(\tR\aBatchID\x128\n" +
	"\aResults\x18\x02 \x03(\v2\x1e.kubemq.SendQueueMessageResultR\aResults\x12\x1e\n" +
	"\n" +
	"HaveErrors\x18\x03 \x01(\bR\n" +
	"HaveErrors\"\xa0\x02\n" +
	"\x16QueueMessageAttributes\x12\x1c\n" +
	"\tTimestamp\x18\x01 \x01(\x03R\tTimestamp\x12\x1a\n" +
	"\bSequence\x18\x02 \x01(\x04R\bSequence\x12\x1c\n" +
	"\tMD5OfBody\x18\x03 \x01(\tR\tMD5OfBody\x12\"\n" +
	"\fReceiveCount\x18\x04 \x01(\x05R\fReceiveCount\x12\x1a\n" +
	"\bReRouted\x18\x05 \x01(\bR\bReRouted\x12,\n" +
	"\x11ReRoutedFromQueue\x18\x06 \x01(\tR\x11ReRoutedFromQueue\x12\"\n" +
	"\fExpirationAt\x18\a \x01(\x03R\fExpirationAt\x12\x1c\n" +
	"\tDelayedTo\x18\b \x01(\x03R\tDelayedTo\"\xba\x01\n" +
	"\x12QueueMessagePolicy\x12,\n" +
	"\x11ExpirationSeconds\x18\x01 \x01(\x05R\x11ExpirationSeconds\x12\"\n" +
	"\fDelaySeconds\x18\x02 \x01(\x05R\fDelaySeconds\x12(\n" +
	"\x0fMaxReceiveCount\x18\x03 \x01(\x05R\x0fMaxReceiveCount\x12(\n" +
	"\x0fMaxReceiveQueue\x18\x04 \x01(\tR\x0fMaxReceiveQueue\"\xc0\x01\n" +
	"\x16SendQueueMessageResult\x12\x1c\n" +
	"\tMessageID\x18\x01 \x01(\tR\tMessageID\x12\x16\n" +
	"\x06SentAt\x18\x02 \x01(\x03R\x06SentAt\x12\"\n" +
	"\fExpirationAt\x18\x03 \x01(\x03R\fExpirationAt\x12\x1c\n" +
	"\tDelayedTo\x18\x04 \x01(\x03R\tDelayedTo\x12\x18\n" +
	"\aIsError\x18\x05 \x01(\bR\aIsError\x12\x14\n" +
	"\x05Error\x18\x06 \x01(\tR\x05Error\"\xe5\x01\n" +
	"\x1bReceiveQueueMessagesRequest\x12\x1c\n" +
	"\tRequestID\x18\x01 \x01(\tR\tRequestID\x12\x1a\n" +
	"\bClientID\x18\x02 \x01(\tR\bClientID\x12\x18\n" +
	"\aChannel\x18\x03 \x01(\tR\aChannel\x120\n" +
	"\x13MaxNumberOfMessages\x18\x04 \x01(\x05R\x13MaxNumberOfMessages\x12(\n" +
	"\x0fWaitTimeSeconds\x18\x05 \x01(\x05R\x0fWaitTimeSeconds\x12\x16\n" +
	"\x06IsPeak\x18\x06 \x01(\bR\x06IsPeak\"\x8c\x02\n" +
	"\x1cReceiveQueueMessagesResponse\x12\x1c\n" +
	"\tRequestID\x18\x01 \x01(\tR\tRequestID\x120\n" +
	"\bMessages\x18\x02 \x03(\v2\x14.kubemq.QueueMessageR\bMessages\x12*\n" +
	"\x10MessagesReceived\x18\x03 \x01(\x05R\x10MessagesReceived\x12(\n" +
	"\x0fMessagesExpired\x18\x04 \x01(\x05R\x0fMessagesExpired\x12\x16\n" +
	"\x06IsPeak\x18\x05 \x01(\bR\x06IsPeak\x12\x18\n" +
	"\aIsError\x18\x06 \x01(\bR\aIsError\x12\x14\n" +
	"\x05Error\x18\a \x01(\tR\x05Error\"\x9a\x01\n" +
	"\x1aAckAllQueueMessagesRequest\x12\x1c\n" +
	"\tRequestID\x18\x01 \x01(\tR\tRequestID\x12\x1a\n" +
	"\bClientID\x18\x02 \x01(\tR\bClientID\x12\x18\n" +
	"\aChannel\x18\x03 \x01(\tR\aChannel\x12(\n" +
	"\x0fWaitTimeSeconds\x18\x04 \x01(\x05R\x0fWaitTimeSeconds\"\x97\x01\n" +
	"\x1bAckAllQueueMessagesResponse\x12\x1c\n" +
	"\tRequestID\x18\x01 \x01(\tR\tRequestID\x12*\n" +
	"\x10AffectedMessages\x18\x02 \x01(\x04R\x10AffectedMessages\x12\x18\n" +
	"\aIsError\x18\x03 \x01(\bR\aIsError\x12\x14\n" +
	"\x05Error\x18\x04 \x01(\tR\x05Error\"\xfb\x02\n" +
	"\x1aStreamQueueMessagesRequest\x12\x1c\n" +
	"\tRequestID\x18\x01 \x01(\tR\tRequestID\x12\x1a\n" +
	"\bClientID\x18\x02 \x01(\tR\bClientID\x12O\n" +
	"\x15StreamRequestTypeData\x18\x03 \x01(\x0e2\x19.kubemq.StreamRequestTypeR\x15StreamRequestTypeData\x12\x18\n" +
	"\aChannel\x18\x04 \x01(\tR\aChannel\x12,\n" +
	"\x11VisibilitySeconds\x18\x05 \x01(\x05R\x11VisibilitySeconds\x12(\n" +
	"\x0fWaitTimeSeconds\x18\x06 \x01(\x05R\x0fWaitTimeSeconds\x12 \n" +
	"\vRefSequence\x18\a \x01(\x04R\vRefSequence\x12>\n" +
	"\x0fModifiedMessage\x18\b \x01(\v2\x14.kubemq.QueueMessageR\x0fModifiedMessage\"\xec\x01\n" +
	"\x1bStreamQueueMessagesResponse\x12\x1c\n" +
	"\tRequestID\x18\x01 \x01(\tR\tRequestID\x12O\n" +
	"\x15StreamRequestTypeData\x18\x02 \x01(\x0e2\x19.kubemq.StreamRequestTypeR\x15StreamRequestTypeData\x12.\n" +
	"\aMessage\x18\x03 \x01(\v2\x14.kubemq.QueueMessageR\aMessage\x12\x18\n" +
	"\aIsError\x18\x04 \x01(\bR\aIsError\x12\x14\n" +
	"\x05Error\x18\x05 \x01(\tR\x05Error\"g\n" +
	"\x15QueuesUpstreamRequest\x12\x1c\n" +
	"\tRequestID\x18\x01 \x01(\tR\tRequestID\x120\n" +
	"\bMessages\x18\x02 \x03(\v2\x14.kubemq.QueueMessageR\bMessages\"\xa6\x01\n" +
	"\x16QueuesUpstreamResponse\x12\"\n" +
	"\fRefRequestID\x18\x01 \x01(\tR\fRefRequestID\x128\n" +
	"\aResults\x18\x02 \x03(\v2\x1e.kubemq.SendQueueMessageResultR\aResults\x12\x18\n" +
	"\aIsError\x18\x03 \x01(\bR\aIsError\x12\x14\n" +
	"\x05Error\x18\x04 \x01(\tR\x05Error\"\x96\x04\n" +
	"\x17QueuesDownstreamRequest\x12\x1c\n" +
	"\tRequestID\x18\x01 \x01(\tR\tRequestID\x12\x1a\n" +
	"\bClientID\x18\x02 \x01(\tR\bClientID\x12M\n" +
	"\x0fRequestTypeData\x18\x03 \x01(\x0e2#.kubemq.QueuesDownstreamRequestTypeR\x0fRequestTypeData\x12\x18\n" +
	"\aChannel\x18\x04 \x01(\tR\aChannel\x12\x1a\n" +
	"\bMaxItems\x18\x05 \x01(\x05R\bMaxItems\x12 \n" +
	"\vWaitTimeout\x18\x06 \x01(\x05R\vWaitTimeout\x12\x18\n" +
	"\aAutoAck\x18\a \x01(\bR\aAutoAck\x12&\n" +
	"\x0eReQueueChannel\x18\b \x01(\tR\x0eReQueueChannel\x12$\n" +
	"\rSequenceRange\x18\t \x03(\x03R\rSequenceRange\x12*\n" +
	"\x10RefTransactionId\x18\n" +
	" \x01(\tR\x10RefTransactionId\x12I\n" +
	"\bMetadata\x18\f \x03(\v2-.kubemq.QueuesDownstreamRequest.MetadataEntryR\bMetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf6\x03\n" +
	"\x18QueuesDownstreamResponse\x12$\n" +
	"\rTransactionId\x18\x01 \x01(\tR\rTransactionId\x12\"\n" +
	"\fRefRequestId\x18\x02 \x01(\tR\fRefRequestId\x12M\n" +
	"\x0fRequestTypeData\x18\x03 \x01(\x0e2#.kubemq.QueuesDownstreamRequestTypeR\x0fRequestTypeData\x120\n" +
	"\bMessages\x18\x04 \x03(\v2\x14.kubemq.QueueMessageR\bMessages\x12$\n" +
	"\rActiveOffsets\x18\x05 \x03(\x03R\rActiveOffsets\x12\x18\n" +
	"\aIsError\x18\x06 \x01(\bR\aIsError\x12\x14\n" +
	"\x05Error\x18\a \x01(\tR\x05Error\x120\n" +
	"\x13TransactionComplete\x18\b \x01(\bR\x13TransactionComplete\x12J\n" +
	"\bMetadata\x18\t \x03(\v2..kubemq.QueuesDownstreamResponse.MetadataEntryR\bMetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xaa\x01\n" +
	"\x11StreamRequestType\x12\x1c\n" +
	"\x18StreamRequestTypeUnknown\x10\x00\x12\x12\n" +
	"\x0eReceiveMessage\x10\x01\x12\x0e\n" +
	"\n" +
	"AckMessage\x10\x02\x12\x11\n" +
	"\rRejectMessage\x10\x03\x12\x14\n" +
	"\x10ModifyVisibility\x10\x04\x12\x11\n" +
	"\rResendMessage\x10\x05\x12\x17\n" +
	"\x13SendModifiedMessage\x10\x06*\xea\x01\n" +
	"\x1bQueuesDownstreamRequestType\x12\x1a\n" +
	"\x16PollRequestTypeUnknown\x10\x00\x12\a\n" +
	"\x03Get\x10\x01\x12\n" +
	"\n" +
	"\x06AckAll\x10\x02\x12\f\n" +
	"\bAckRange\x10\x03\x12\v\n" +
	"\aNAckAll\x10\x04\x12\r\n" +
	"\tNAckRange\x10\x05\x12\x0e\n" +
	"\n" +
	"ReQueueAll\x10\x06\x12\x10\n" +
	"\fReQueueRange\x10\a\x12\x11\n" +
	"\rActiveOffsets\x10\b\x12\x15\n" +
	"\x11TransactionStatus\x10\t\x12\x11\n" +
	"\rCloseByClient\x10\n" +
	"\x12\x11\n" +
	"\rCloseByServer\x10\v2\x93\b\n" +
	"\x06kubemq\x12,\n" +
	"\tSendEvent\x12\r.kubemq.Event\x1a\x0e.kubemq.Result\"\x00\x127\n" +
	"\x10SendEventsStream\x12\r.kubemq.Event\x1a\x0e.kubemq.Result\"\x00(\x010\x01\x12@\n" +
	"\x11SubscribeToEvents\x12\x11.kubemq.Subscribe\x1a\x14.kubemq.EventReceive\"\x000\x01\x12=\n" +
	"\x13SubscribeToRequests\x12\x11.kubemq.Subscribe\x1a\x0f.kubemq.Request\"\x000\x01\x122\n" +
	"\vSendRequest\x12\x0f.kubemq.Request\x1a\x10.kubemq.Response\"\x00\x121\n" +
	"\fSendResponse\x12\x10.kubemq.Response\x1a\r.kubemq.Empty\"\x00\x12J\n" +
	"\x10SendQueueMessage\x12\x14.kubemq.QueueMessage\x1a\x1e.kubemq.SendQueueMessageResult\"\x00\x12a\n" +
	"\x16SendQueueMessagesBatch\x12!.kubemq.QueueMessagesBatchRequest\x1a\".kubemq.QueueMessagesBatchResponse\"\x00\x12c\n" +
	"\x14ReceiveQueueMessages\x12#.kubemq.ReceiveQueueMessagesRequest\x1a$.kubemq.ReceiveQueueMessagesResponse\"\x00\x12c\n" +
	"\x12StreamQueueMessage\x12\".kubemq.StreamQueueMessagesRequest\x1a#.kubemq.StreamQueueMessagesResponse\"\x00(\x010\x01\x12`\n" +
	"\x13AckAllQueueMessages\x12\".kubemq.AckAllQueueMessagesRequest\x1a#.kubemq.AckAllQueueMessagesResponse\"\x00\x12+\n" +
	"\x04Ping\x12\r.kubemq.Empty\x1a\x12.kubemq.PingResult\"\x00\x12[\n" +
	"\x10QueuesDownstream\x12\x1f.kubemq.QueuesDownstreamRequest\x1a .kubemq.QueuesDownstreamResponse\"\x00(\x010\x01\x12U\n" +
	"\x0eQueuesUpstream\x12\x1d.kubemq.QueuesUpstreamRequest\x1a\x1e.kubemq.QueuesUpstreamResponse\"\x00(\x010\x01B&Z$github.com/kubemq-io/kubemq-go/v2/pbb\x06proto3"

var (
	file_kubemq_proto_rawDescOnce sync.Once
	file_kubemq_proto_rawDescData []byte
)

func file_kubemq_proto_rawDescGZIP() []byte {
	file_kubemq_proto_rawDescOnce.Do(func() {
		file_kubemq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubemq_proto_rawDesc), len(file_kubemq_proto_rawDesc)))
	})
	return file_kubemq_proto_rawDescData
}

var file_kubemq_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_kubemq_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_kubemq_proto_goTypes = []any{
	(StreamRequestType)(0),               // 0: kubemq.StreamRequestType
	(QueuesDownstreamRequestType)(0),     // 1: kubemq.QueuesDownstreamRequestType
	(Subscribe_SubscribeType)(0),         // 2: kubemq.Subscribe.SubscribeType
	(Subscribe_EventsStoreType)(0),       // 3: kubemq.Subscribe.EventsStoreType
	(Request_RequestType)(0),             // 4: kubemq.Request.RequestType
	(*PingResult)(nil),                   // 5: kubemq.PingResult
	(*Empty)(nil),                        // 6: kubemq.Empty
	(*Result)(nil),                       // 7: kubemq.Result
	(*Event)(nil),                        // 8: kubemq.Event
	(*EventReceive)(nil),                 // 9: kubemq.EventReceive
	(*Subscribe)(nil),                    // 10: kubemq.Subscribe
	(*Request)(nil),                      // 11: kubemq.Request
	(*Response)(nil),                     // 12: kubemq.Response
	(*QueueMessage)(nil),                 // 13: kubemq.QueueMessage
	(*QueueMessagesBatchRequest)(nil),    // 14: kubemq.QueueMessagesBatchRequest
	(*QueueMessagesBatchResponse)(nil),   // 15: kubemq.QueueMessagesBatchResponse
	(*QueueMessageAttributes)(nil),       // 16: kubemq.QueueMessageAttributes
	(*QueueMessagePolicy)(nil),           // 17: kubemq.QueueMessagePolicy
	(*SendQueueMessageResult)(nil),       // 18: kubemq.SendQueueMessageResult
	(*ReceiveQueueMessagesRequest)(nil),  // 19: kubemq.ReceiveQueueMessagesRequest
	(*ReceiveQueueMessagesResponse)(nil), // 20: kubemq.ReceiveQueueMessagesResponse
	(*AckAllQueueMessagesRequest)(nil),   // 21: kubemq.AckAllQueueMessagesRequest
	(*AckAllQueueMessagesResponse)(nil),  // 22: kubemq.AckAllQueueMessagesResponse
	(*StreamQueueMessagesRequest)(nil),   // 23: kubemq.StreamQueueMessagesRequest
	(*StreamQueueMessagesResponse)(nil),  // 24: kubemq.StreamQueueMessagesResponse
	(*QueuesUpstreamRequest)(nil),        // 25: kubemq.QueuesUpstreamRequest
	(*QueuesUpstreamResponse)(nil),       // 26: kubemq.QueuesUpstreamResponse
	(*QueuesDownstreamRequest)(nil),      // 27: kubemq.QueuesDownstreamRequest
	(*QueuesDownstreamResponse)(nil),     // 28: kubemq.QueuesDownstreamResponse
	nil,                                  // 29: kubemq.Event.TagsEntry
	nil,                                  // 30: kubemq.EventReceive.TagsEntry
	nil,                                  // 31: kubemq.Request.TagsEntry
	nil,                                  // 32: kubemq.Response.TagsEntry
	nil,                                  // 33: kubemq.QueueMessage.TagsEntry
	nil,                                  // 34: kubemq.QueuesDownstreamRequest.MetadataEntry
	nil,                                  // 35: kubemq.QueuesDownstreamResponse.MetadataEntry
}
var file_kubemq_proto_depIdxs = []int32{
	29, // 0: kubemq.Event.Tags:type_name -> kubemq.Event.TagsEntry
	30, // 1: kubemq.EventReceive.Tags:type_name -> kubemq.EventReceive.TagsEntry
	2,  // 2: kubemq.Subscribe.SubscribeTypeData:type_name -> kubemq.Subscribe.SubscribeType
	3,  // 3: kubemq.Subscribe.EventsStoreTypeData:type_name -> kubemq.Subscribe.EventsStoreType
	4,  // 4: kubemq.Request.RequestTypeData:type_name -> kubemq.Request.RequestType
	31, // 5: kubemq.Request.Tags:type_name -> kubemq.Request.TagsEntry
	32, // 6: kubemq.Response.Tags:type_name -> kubemq.Response.TagsEntry
	33, // 7: kubemq.QueueMessage.Tags:type_name -> kubemq.QueueMessage.TagsEntry
	16, // 8: kubemq.QueueMessage.Attributes:type_name -> kubemq.QueueMessageAttributes
	17, // 9: kubemq.QueueMessage.Policy:type_name -> kubemq.QueueMessagePolicy
	13, // 10: kubemq.QueueMessagesBatchRequest.Messages:type_name -> kubemq.QueueMessage
	18, // 11: kubemq.QueueMessagesBatchResponse.Results:type_name -> kubemq.SendQueueMessageResult
	13, // 12: kubemq.ReceiveQueueMessagesResponse.Messages:type_name -> kubemq.QueueMessage
	0,  // 13: kubemq.StreamQueueMessagesRequest.StreamRequestTypeData:type_name -> kubemq.StreamRequestType
	13, // 14: kubemq.StreamQueueMessagesRequest.ModifiedMessage:type_name -> kubemq.QueueMessage
	0,  // 15: kubemq.StreamQueueMessagesResponse.StreamRequestTypeData:type_name -> kubemq.StreamRequestType
	13, // 16: kubemq.StreamQueueMessagesResponse.Message:type_name -> kubemq.QueueMessage
	13, // 17: kubemq.QueuesUpstreamRequest.Messages:type_name -> kubemq.QueueMessage
	18, // 18: kubemq.QueuesUpstreamResponse.Results:type_name -> kubemq.SendQueueMessageResult
	1,  // 19: kubemq.QueuesDownstreamRequest.RequestTypeData:type_name -> kubemq.QueuesDownstreamRequestType
	34, // 20: kubemq.QueuesDownstreamRequest.Metadata:type_name -> kubemq.QueuesDownstreamRequest.MetadataEntry
	1,  // 21: kubemq.QueuesDownstreamResponse.RequestTypeData:type_name -> kubemq.QueuesDownstreamRequestType
	13, // 22: kubemq.QueuesDownstreamResponse.Messages:type_name -> kubemq.QueueMessage
	35, // 23: kubemq.QueuesDownstreamResponse.Metadata:type_name -> kubemq.QueuesDownstreamResponse.MetadataEntry
	8,  // 24: kubemq.kubemq.SendEvent:input_type -> kubemq.Event
	8,  // 25: kubemq.kubemq.SendEventsStream:input_type -> kubemq.Event
	10, // 26: kubemq.kubemq.SubscribeToEvents:input_type -> kubemq.Subscribe
	10, // 27: kubemq.kubemq.SubscribeToRequests:input_type -> kubemq.Subscribe
	11, // 28: kubemq.kubemq.SendRequest:input_type -> kubemq.Request
	12, // 29: kubemq.kubemq.SendResponse:input_type -> kubemq.Response
	13, // 30: kubemq.kubemq.SendQueueMessage:input_type -> kubemq.QueueMessage
	14, // 31: kubemq.kubemq.SendQueueMessagesBatch:input_type -> kubemq.QueueMessagesBatchRequest
	19, // 32: kubemq.kubemq.ReceiveQueueMessages:input_type -> kubemq.ReceiveQueueMessagesRequest
	23, // 33: kubemq.kubemq.StreamQueueMessage:input_type -> kubemq.StreamQueueMessagesRequest
	21, // 34: kubemq.kubemq.AckAllQueueMessages:input_type -> kubemq.AckAllQueueMessagesRequest
	6,  // 35: kubemq.kubemq.Ping:input_type -> kubemq.Empty
	27, // 36: kubemq.kubemq.QueuesDownstream:input_type -> kubemq.QueuesDownstreamRequest
	25, // 37: kubemq.kubemq.QueuesUpstream:input_type -> kubemq.QueuesUpstreamRequest
	7,  // 38: kubemq.kubemq.SendEvent:output_type -> kubemq.Result
	7,  // 39: kubemq.kubemq.SendEventsStream:output_type -> kubemq.Result
	9,  // 40: kubemq.kubemq.SubscribeToEvents:output_type -> kubemq.EventReceive
	11, // 41: kubemq.kubemq.SubscribeToRequests:output_type -> kubemq.Request
	12, // 42: kubemq.kubemq.SendRequest:output_type -> kubemq.Response
	6,  // 43: kubemq.kubemq.SendResponse:output_type -> kubemq.Empty
	18, // 44: kubemq.kubemq.SendQueueMessage:output_type -> kubemq.SendQueueMessageResult
	15, // 45: kubemq.kubemq.SendQueueMessagesBatch:output_type -> kubemq.QueueMessagesBatchResponse
	20, // 46: kubemq.kubemq.ReceiveQueueMessages:output_type -> kubemq.ReceiveQueueMessagesResponse
	24, // 47: kubemq.kubemq.StreamQueueMessage:output_type -> kubemq.StreamQueueMessagesResponse
	22, // 48: kubemq.kubemq.AckAllQueueMessages:output_type -> kubemq.AckAllQueueMessagesResponse
	5,  // 49: kubemq.kubemq.Ping:output_type -> kubemq.PingResult
	28, // 50: kubemq.kubemq.QueuesDownstream:output_type -> kubemq.QueuesDownstreamResponse
	26, // 51: kubemq.kubemq.QueuesUpstream:output_type -> kubemq.QueuesUpstreamResponse
	38, // [38:52] is the sub-list for method output_type
	24, // [24:38] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_kubemq_proto_init() }
func file_kubemq_proto_init() {
	if File_kubemq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubemq_proto_rawDesc), len(file_kubemq_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kubemq_proto_goTypes,
		DependencyIndexes: file_kubemq_proto_depIdxs,
		EnumInfos:         file_kubemq_proto_enumTypes,
		MessageInfos:      file_kubemq_proto_msgTypes,
	}.Build()
	File_kubemq_proto = out.File
	file_kubemq_proto_goTypes = nil
	file_kubemq_proto_depIdxs = nil
}
