// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: kubemq.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Kubemq_SendEvent_FullMethodName              = "/kubemq.kubemq/SendEvent"
	Kubemq_SendEventsStream_FullMethodName       = "/kubemq.kubemq/SendEventsStream"
	Kubemq_SubscribeToEvents_FullMethodName      = "/kubemq.kubemq/SubscribeToEvents"
	Kubemq_SubscribeToRequests_FullMethodName    = "/kubemq.kubemq/SubscribeToRequests"
	Kubemq_SendRequest_FullMethodName            = "/kubemq.kubemq/SendRequest"
	Kubemq_SendResponse_FullMethodName           = "/kubemq.kubemq/SendResponse"
	Kubemq_SendQueueMessage_FullMethodName       = "/kubemq.kubemq/SendQueueMessage"
	Kubemq_SendQueueMessagesBatch_FullMethodName = "/kubemq.kubemq/SendQueueMessagesBatch"
	Kubemq_ReceiveQueueMessages_FullMethodName   = "/kubemq.kubemq/ReceiveQueueMessages"
	Kubemq_StreamQueueMessage_FullMethodName     = "/kubemq.kubemq/StreamQueueMessage"
	Kubemq_AckAllQueueMessages_FullMethodName    = "/kubemq.kubemq/AckAllQueueMessages"
	Kubemq_Ping_FullMethodName                   = "/kubemq.kubemq/Ping"
	Kubemq_QueuesDownstream_FullMethodName       = "/kubemq.kubemq/QueuesDownstream"
	Kubemq_QueuesUpstream_FullMethodName         = "/kubemq.kubemq/QueuesUpstream"
)

// KubemqClient is the client API for Kubemq service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KubemqClient interface {
	SendEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Result, error)
	SendEventsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Event, Result], error)
	SubscribeToEvents(ctx context.Context, in *Subscribe, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventReceive], error)
	SubscribeToRequests(ctx context.Context, in *Subscribe, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Request], error)
	SendRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	SendResponse(ctx context.Context, in *Response, opts ...grpc.CallOption) (*Empty, error)
	SendQueueMessage(ctx context.Context, in *QueueMessage, opts ...grpc.CallOption) (*SendQueueMessageResult, error)
	SendQueueMessagesBatch(ctx context.Context, in *QueueMessagesBatchRequest, opts ...grpc.CallOption) (*QueueMessagesBatchResponse, error)
	ReceiveQueueMessages(ctx context.Context, in *ReceiveQueueMessagesRequest, opts ...grpc.CallOption) (*ReceiveQueueMessagesResponse, error)
	StreamQueueMessage(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamQueueMessagesRequest, StreamQueueMessagesResponse], error)
	AckAllQueueMessages(ctx context.Context, in *AckAllQueueMessagesRequest, opts ...grpc.CallOption) (*AckAllQueueMessagesResponse, error)
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResult, error)
	QueuesDownstream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[QueuesDownstreamRequest, QueuesDownstreamResponse], error)
	QueuesUpstream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[QueuesUpstreamRequest, QueuesUpstreamResponse], error)
}

type kubemqClient struct {
	cc grpc.ClientConnInterface
}

func NewKubemqClient(cc grpc.ClientConnInterface) KubemqClient {
	return &kubemqClient{cc}
}

func (c *kubemqClient) SendEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, Kubemq_SendEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubemqClient) SendEventsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Event, Result], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Kubemq_ServiceDesc.Streams[0], Kubemq_SendEventsStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Event, Result]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kubemq_SendEventsStreamClient = grpc.BidiStreamingClient[Event, Result]

func (c *kubemqClient) SubscribeToEvents(ctx context.Context, in *Subscribe, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventReceive], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Kubemq_ServiceDesc.Streams[1], Kubemq_SubscribeToEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Subscribe, EventReceive]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kubemq_SubscribeToEventsClient = grpc.ServerStreamingClient[EventReceive]

func (c *kubemqClient) SubscribeToRequests(ctx context.Context, in *Subscribe, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Request], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Kubemq_ServiceDesc.Streams[2], Kubemq_SubscribeToRequests_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Subscribe, Request]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kubemq_SubscribeToRequestsClient = grpc.ServerStreamingClient[Request]

func (c *kubemqClient) SendRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Kubemq_SendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubemqClient) SendResponse(ctx context.Context, in *Response, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Kubemq_SendResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubemqClient) SendQueueMessage(ctx context.Context, in *QueueMessage, opts ...grpc.CallOption) (*SendQueueMessageResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendQueueMessageResult)
	err := c.cc.Invoke(ctx, Kubemq_SendQueueMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubemqClient) SendQueueMessagesBatch(ctx context.Context, in *QueueMessagesBatchRequest, opts ...grpc.CallOption) (*QueueMessagesBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueueMessagesBatchResponse)
	err := c.cc.Invoke(ctx, Kubemq_SendQueueMessagesBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubemqClient) ReceiveQueueMessages(ctx context.Context, in *ReceiveQueueMessagesRequest, opts ...grpc.CallOption) (*ReceiveQueueMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReceiveQueueMessagesResponse)
	err := c.cc.Invoke(ctx, Kubemq_ReceiveQueueMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubemqClient) StreamQueueMessage(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamQueueMessagesRequest, StreamQueueMessagesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Kubemq_ServiceDesc.Streams[3], Kubemq_StreamQueueMessage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamQueueMessagesRequest, StreamQueueMessagesResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kubemq_StreamQueueMessageClient = grpc.BidiStreamingClient[StreamQueueMessagesRequest, StreamQueueMessagesResponse]

func (c *kubemqClient) AckAllQueueMessages(ctx context.Context, in *AckAllQueueMessagesRequest, opts ...grpc.CallOption) (*AckAllQueueMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckAllQueueMessagesResponse)
	err := c.cc.Invoke(ctx, Kubemq_AckAllQueueMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubemqClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResult)
	err := c.cc.Invoke(ctx, Kubemq_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubemqClient) QueuesDownstream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[QueuesDownstreamRequest, QueuesDownstreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Kubemq_ServiceDesc.Streams[4], Kubemq_QueuesDownstream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueuesDownstreamRequest, QueuesDownstreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kubemq_QueuesDownstreamClient = grpc.BidiStreamingClient[QueuesDownstreamRequest, QueuesDownstreamResponse]

func (c *kubemqClient) QueuesUpstream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[QueuesUpstreamRequest, QueuesUpstreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Kubemq_ServiceDesc.Streams[5], Kubemq_QueuesUpstream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueuesUpstreamRequest, QueuesUpstreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kubemq_QueuesUpstreamClient = grpc.BidiStreamingClient[QueuesUpstreamRequest, QueuesUpstreamResponse]

// KubemqServer is the server API for Kubemq service.
// All implementations must embed UnimplementedKubemqServer
// for forward compatibility.
type KubemqServer interface {
	SendEvent(context.Context, *Event) (*Result, error)
	SendEventsStream(grpc.BidiStreamingServer[Event, Result]) error
	SubscribeToEvents(*Subscribe, grpc.ServerStreamingServer[EventReceive]) error
	SubscribeToRequests(*Subscribe, grpc.ServerStreamingServer[Request]) error
	SendRequest(context.Context, *Request) (*Response, error)
	SendResponse(context.Context, *Response) (*Empty, error)
	SendQueueMessage(context.Context, *QueueMessage) (*SendQueueMessageResult, error)
	SendQueueMessagesBatch(context.Context, *QueueMessagesBatchRequest) (*QueueMessagesBatchResponse, error)
	ReceiveQueueMessages(context.Context, *ReceiveQueueMessagesRequest) (*ReceiveQueueMessagesResponse, error)
	StreamQueueMessage(grpc.BidiStreamingServer[StreamQueueMessagesRequest, StreamQueueMessagesResponse]) error
	AckAllQueueMessages(context.Context, *AckAllQueueMessagesRequest) (*AckAllQueueMessagesResponse, error)
	Ping(context.Context, *Empty) (*PingResult, error)
	QueuesDownstream(grpc.BidiStreamingServer[QueuesDownstreamRequest, QueuesDownstreamResponse]) error
	QueuesUpstream(grpc.BidiStreamingServer[QueuesUpstreamRequest, QueuesUpstreamResponse]) error
	mustEmbedUnimplementedKubemqServer()
}

// UnimplementedKubemqServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKubemqServer struct{}

func (UnimplementedKubemqServer) SendEvent(context.Context, *Event) (*Result, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEvent not implemented")
}
func (UnimplementedKubemqServer) SendEventsStream(grpc.BidiStreamingServer[Event, Result]) error {
	return status.Error(codes.Unimplemented, "method SendEventsStream not implemented")
}
func (UnimplementedKubemqServer) SubscribeToEvents(*Subscribe, grpc.ServerStreamingServer[EventReceive]) error {
	return status.Error(codes.Unimplemented, "method SubscribeToEvents not implemented")
}
func (UnimplementedKubemqServer) SubscribeToRequests(*Subscribe, grpc.ServerStreamingServer[Request]) error {
	return status.Error(codes.Unimplemented, "method SubscribeToRequests not implemented")
}
func (UnimplementedKubemqServer) SendRequest(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SendRequest not implemented")
}
func (UnimplementedKubemqServer) SendResponse(context.Context, *Response) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendResponse not implemented")
}
func (UnimplementedKubemqServer) SendQueueMessage(context.Context, *QueueMessage) (*SendQueueMessageResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SendQueueMessage not implemented")
}
func (UnimplementedKubemqServer) SendQueueMessagesBatch(context.Context, *QueueMessagesBatchRequest) (*QueueMessagesBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendQueueMessagesBatch not implemented")
}
func (UnimplementedKubemqServer) ReceiveQueueMessages(context.Context, *ReceiveQueueMessagesRequest) (*ReceiveQueueMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceiveQueueMessages not implemented")
}
func (UnimplementedKubemqServer) StreamQueueMessage(grpc.BidiStreamingServer[StreamQueueMessagesRequest, StreamQueueMessagesResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamQueueMessage not implemented")
}
func (UnimplementedKubemqServer) AckAllQueueMessages(context.Context, *AckAllQueueMessagesRequest) (*AckAllQueueMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckAllQueueMessages not implemented")
}
func (UnimplementedKubemqServer) Ping(context.Context, *Empty) (*PingResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedKubemqServer) QueuesDownstream(grpc.BidiStreamingServer[QueuesDownstreamRequest, QueuesDownstreamResponse]) error {
	return status.Error(codes.Unimplemented, "method QueuesDownstream not implemented")
}
func (UnimplementedKubemqServer) QueuesUpstream(grpc.BidiStreamingServer[QueuesUpstreamRequest, QueuesUpstreamResponse]) error {
	return status.Error(codes.Unimplemented, "method QueuesUpstream not implemented")
}
func (UnimplementedKubemqServer) mustEmbedUnimplementedKubemqServer() {}
func (UnimplementedKubemqServer) testEmbeddedByValue()                {}

// UnsafeKubemqServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KubemqServer will
// result in compilation errors.
type UnsafeKubemqServer interface {
	mustEmbedUnimplementedKubemqServer()
}

func RegisterKubemqServer(s grpc.ServiceRegistrar, srv KubemqServer) {
	// If the following call panics, it indicates UnimplementedKubemqServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Kubemq_ServiceDesc, srv)
}

func _Kubemq_SendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubemqServer).SendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kubemq_SendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubemqServer).SendEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubemq_SendEventsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KubemqServer).SendEventsStream(&grpc.GenericServerStream[Event, Result]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kubemq_SendEventsStreamServer = grpc.BidiStreamingServer[Event, Result]

func _Kubemq_SubscribeToEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Subscribe)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KubemqServer).SubscribeToEvents(m, &grpc.GenericServerStream[Subscribe, EventReceive]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kubemq_SubscribeToEventsServer = grpc.ServerStreamingServer[EventReceive]

func _Kubemq_SubscribeToRequests_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Subscribe)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KubemqServer).SubscribeToRequests(m, &grpc.GenericServerStream[Subscribe, Request]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kubemq_SubscribeToRequestsServer = grpc.ServerStreamingServer[Request]

func _Kubemq_SendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubemqServer).SendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kubemq_SendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubemqServer).SendRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubemq_SendResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Response)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubemqServer).SendResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kubemq_SendResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubemqServer).SendResponse(ctx, req.(*Response))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubemq_SendQueueMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubemqServer).SendQueueMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kubemq_SendQueueMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubemqServer).SendQueueMessage(ctx, req.(*QueueMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubemq_SendQueueMessagesBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueMessagesBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubemqServer).SendQueueMessagesBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kubemq_SendQueueMessagesBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubemqServer).SendQueueMessagesBatch(ctx, req.(*QueueMessagesBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubemq_ReceiveQueueMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveQueueMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubemqServer).ReceiveQueueMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kubemq_ReceiveQueueMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubemqServer).ReceiveQueueMessages(ctx, req.(*ReceiveQueueMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubemq_StreamQueueMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KubemqServer).StreamQueueMessage(&grpc.GenericServerStream[StreamQueueMessagesRequest, StreamQueueMessagesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kubemq_StreamQueueMessageServer = grpc.BidiStreamingServer[StreamQueueMessagesRequest, StreamQueueMessagesResponse]

func _Kubemq_AckAllQueueMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckAllQueueMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubemqServer).AckAllQueueMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kubemq_AckAllQueueMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubemqServer).AckAllQueueMessages(ctx, req.(*AckAllQueueMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubemq_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubemqServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kubemq_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubemqServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubemq_QueuesDownstream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KubemqServer).QueuesDownstream(&grpc.GenericServerStream[QueuesDownstreamRequest, QueuesDownstreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kubemq_QueuesDownstreamServer = grpc.BidiStreamingServer[QueuesDownstreamRequest, QueuesDownstreamResponse]

func _Kubemq_QueuesUpstream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KubemqServer).QueuesUpstream(&grpc.GenericServerStream[QueuesUpstreamRequest, QueuesUpstreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Kubemq_QueuesUpstreamServer = grpc.BidiStreamingServer[QueuesUpstreamRequest, QueuesUpstreamResponse]

// Kubemq_ServiceDesc is the grpc.ServiceDesc for Kubemq service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kubemq_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kubemq.kubemq",
	HandlerType: (*KubemqServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEvent",
			Handler:    _Kubemq_SendEvent_Handler,
		},
		{
			MethodName: "SendRequest",
			Handler:    _Kubemq_SendRequest_Handler,
		},
		{
			MethodName: "SendResponse",
			Handler:    _Kubemq_SendResponse_Handler,
		},
		{
			MethodName: "SendQueueMessage",
			Handler:    _Kubemq_SendQueueMessage_Handler,
		},
		{
			MethodName: "SendQueueMessagesBatch",
			Handler:    _Kubemq_SendQueueMessagesBatch_Handler,
		},
		{
			MethodName: "ReceiveQueueMessages",
			Handler:    _Kubemq_ReceiveQueueMessages_Handler,
		},
		{
			MethodName: "AckAllQueueMessages",
			Handler:    _Kubemq_AckAllQueueMessages_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Kubemq_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendEventsStream",
			Handler:       _Kubemq_SendEventsStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeToEvents",
			Handler:       _Kubemq_SubscribeToEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeToRequests",
			Handler:       _Kubemq_SubscribeToRequests_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamQueueMessage",
			Handler:       _Kubemq_StreamQueueMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "QueuesDownstream",
			Handler:       _Kubemq_QueuesDownstream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "QueuesUpstream",
			Handler:       _Kubemq_QueuesUpstream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "kubemq.proto",
}
